author = "Ruby Quail"
description = "Ruby is an designer living in Melbourne. She is interested in socially conscious design and achieving positive social change through the use of digital technology. This is her website"
websiteUrl = "https://rubyquail.design"
mailUrl = "mailto:enquiries@rubyquail.design"
twitterUrl = "https://twitter.com/RubyQuailDesign"
linkedInUrl = "https://www.linkedin.com/in/rubyquail"
instagramUrl = "https://instagram.com/rubyquaildesign"
resumeUrl = "https://rubyquail.design/documents/cv"
blobUrl = "https://files.rubyquail.design"
ghUrl = "https://github.com/Rupertofly"
medUrl = "https://rubyquaildesign.medium.com"

[[links]]
title = "My Website"
link = "/"

[[links]]
title = "Pronouns and etc."
link = "https://en.pronouns.page/@rubyquail"

[[links]]
title = "2021 Trans Awareness Week: My Experience"
link = "https://rubyquaildesign.medium.com/trans-awareness-week-2021-my-experience-4b3e65875a81"

[[links]]
title = "World Industrial Design Day 2021 — Gender, Sexuality and Design panel"
link = "https://www.eventbrite.com/e/qut-world-industrial-design-day-2021-panel-discussion-tickets-157948996701"

[[links]]
title = "Ruby's 2021 list of things that made her think about gender"
link = "https://rubyquaildesign.medium.com/rubys-2021-list-of-things-that-made-her-think-about-gender-430ec250e834"

[[links]]
title = "So I want to talk about visibility — Medium"
link = "https://rubyquaildesign.medium.com/i-want-to-talk-about-visibility-bb51a506878c"

[[links]]
title = "Gender Diverse in Design - Recording"
link = "https://vimeo.com/531495245"
